[package]
name = "HLHD"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.1"
bevy_ecs = "0.12.1"
bevy_rapier2d = "0.23.0" # Don't change, compiler is fucky
leafwing-input-manager = "0.11.2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1